import { z } from "zod";
import { initializeCampaignLab, getCampaignLabStatus, allocateCampaignLabBudget, commitCampaignLabReward, recordCampaignLabEvent } from "@/lib/cofounder-campaign-lab";

export function registerCampaignLabTools(mcp: any) {
  mcp.tool("initialize_campaign_lab", "Initialize the flexible hard-capped R3,000 experiment split between artists and friends/fans.", { budgetZAR: z.number().min(0).max(3000).default(3000), artistsAllocationZAR: z.number().min(0).default(1800), friendsAllocationZAR: z.number().min(0).default(1200), reserveZAR: z.number().min(0).default(0) }, async (x: any) => ({ content: [{ type: "text", text: JSON.stringify(await initializeCampaignLab(x.budgetZAR, x.artistsAllocationZAR, x.friendsAllocationZAR, x.reserveZAR), null, 2) }] }));
  mcp.tool("get_campaign_lab_status", "Show the artist/friends split, commitments, genuine transactions, and remaining R3,000 budget.", {}, async () => ({ content: [{ type: "text", text: JSON.stringify(await getCampaignLabStatus(), null, 2) }] }));
  mcp.tool("allocate_campaign_lab_budget", "Rebalance the artist and friends/fan allocations without exceeding the hard ceiling or unfunding existing commitments.", { artistsAllocationZAR: z.number().min(0), friendsAllocationZAR: z.number().min(0), reserveZAR: z.number().min(0).default(0) }, async (x: any) => ({ content: [{ type: "text", text: JSON.stringify(await allocateCampaignLabBudget(x.artistsAllocationZAR, x.friendsAllocationZAR, x.reserveZAR), null, 2) }] }));
  mcp.tool("commit_campaign_lab_reward", "Reserve an incentive against one track. This never sends money and enforces both track and global budget limits.", { track: z.enum(["artists", "friends"]), recipient: z.string().min(1).max(300), amountZAR: z.number().min(0), reason: z.string().min(3).max(1000), evidence: z.string().min(3).max(2000) }, async (x: any) => ({ content: [{ type: "text", text: JSON.stringify({ commitment: await commitCampaignLabReward(x.track, x.recipient, x.amountZAR, x.reason, x.evidence), approvalRequired: true }, null, 2) }] }));
  mcp.tool("record_campaign_lab_event", "Record artist or friends/fan activation and genuine transaction events. Transactions require positive value and evidence.", { track: z.enum(["artists", "friends"]), type: z.enum(["prospect", "contacted", "signup", "artist_activated", "fan_activated", "genuine_transaction", "repeat_transaction", "referral"]), subject: z.string().min(1).max(300), evidence: z.string().min(3).max(2000), valueZAR: z.number().min(0).optional() }, async (x: any) => ({ content: [{ type: "text", text: JSON.stringify(await recordCampaignLabEvent(x), null, 2) }] }));
}
